# Project information
site_name: TechnoLuc Documentation
site_url: https://technoluc.github.io/technoluc.github.io/
site_author: TechnoLuc
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project

# Repository
repo_name: technoluc/technoluc.github.io
repo_url: https://github.com/technoluc/technoluc.github.io
edit_uri: edit/main/docs/


# Theme
theme:
  name: material
  logo: assets/TL.png
  favicon: assets/TL.png
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Bash:
    - bash/index.md
    - Useful Commands: bash/useful_commands.md
    - bashrc: bash/bashrc.md
    - For.. Loops: bash/loops.md
    - Scripts: bash/scripts.md
  - Linux:
    - linux/index.md
    - Hostname: linux/set-hostname.md
    - Networking: linux/networking.md
    - NFS: linux/nfs.md
    - Sed: linux/sed.md
    - Timezone: linux/set-timezone.md
  - Docker: 
    - docker/index.md
    - Docker CLI: docker/docker-cli.md
    - Docker Compose: docker/docker-compose.md
  - Python: 
    - python/index.md
    - Virtual Environment: python/virtualenv.md
  - Windows:
    - windows/index.md
    - Activate Office 2021: windows/office.md
    - Activate Windows 10/11: windows/windows.md
    - WinGet: windows/winget.md
    - SFC: windows/sfc.md
  - Excel:
    - excel/index.md
    - Addresses: excel/addresses.md
    - Formulas: excel/formulas.md
  - Markdown:
    - markdown/index.md
    - Cheatsheet 1: markdown/markdown-cheat-sheet.md
    - Cheatsheet 2: markdown/markdown-cheatsheet.md
  - MkDocs:
    - mkdocs/index.md


